### ISSUE TITLE
Regarding Payment Gateway

### ISSUE THREAD

**Issue by nk1102** [manishMandal02/growmart-backend#1]
Hi ,
I would like to suggest you to please work on the indian payment system such as paytm for this app 
and help me regarding this .
It would be really helpful 
thanks

**Comment by manishMandal02** [comment]
Hi, 
Thank you for showing interest in the project.

What help do you want from me?

**Comment by nk1102** [comment]
I want Help how to integrate 
Paytm in the project that you have created 
as it is a bit complicated 

if you can work on the Payment gateway such as Paytm , or Razorpay in this project it would be really helpful 
Thanks

**Comment by nk1102** [comment]
Any response sir?

**Comment by manishMandal02** [comment]
> Any response sir?

Let's connect.
Email me at manishmandalj@gmail.com

Thanks!

**Comment by nk1102** [comment]
no
